name: Auto CSV Conversion

on:
  push:
    paths:
      - 'input_files/*.csv'  # Trigger only when a CSV is pushed to this folder

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Find and process the uploaded CSV file
      run: |
        mkdir -p output_files
        input_file=$(find input_files -name '*.csv' | head -n 1)
        echo "Found CSV file: $input_file"
        python convert.py "$input_file"

    - name: Upload the resulting CSV file
      uses: actions/upload-artifact@v2
      with:
        name: output-file
        path: output_files/output.csv
